# https://taskfile.dev

version: '3'

vars:
# clip-vit-base-patch32
  backbone: '{{.backbone | default "{{.backbone}}"}}'
  seed: '{{.seed | default 0}}'
  debug: '{{.debug | default false}}'
  main: '{{.main | default "data_select.py"}}'
  overwrite: '{{.overwrite | default false}}'

tasks:
  feature:
    cmds:
      - python main.py mode=feature_extraction backbone={{.backbone}}
  ls:
    cmds:
      - |
        python {{.main}} -m \
        dataset=cifar10 \
        backbone={{.backbone}} \
        selection=leverage_score \
        selection.space=feature \
        selection.fraction=0.001,0.01,0.1,0.2,0.4,0.6,0.8 \
        selection.source=pretrained \
        selection.B=10 \
        selection.k=512 \
        selection.use_raw_G=False \
        selection.use_residual=False \
        hydra/launcher=basic
    silent: true
  ls-cifar10-0.001:
    cmds:
      - |
        python {{.main}} -m \
        dataset=cifar10 \
        backbone={{.backbone}} \
        selection=leverage_score \
        selection.space=feature \
        selection.fraction=0.001 \
        selection.source=pretrained \
        selection.B=10 \
        selection.k=512 \
        selection.use_raw_G=False \
        selection.use_residual=False \
        overwrite=True \
        hydra/launcher=basic
    silent: false
  leverage_score-cifar10_binary-0.001:
    cmds:
      - |
        python {{.main}} -m \
        dataset=cifar10 \
        backbone={{.backbone}} \
        selection=leverage_score \
        selection.space=binary \
        selection.fraction=0.001 \
        selection.source=pretrained \
        selection.B=10 \
        selection.k=512 \
        selection.use_raw_G=False \
        selection.use_residual=False \
        overwrite=True \
        hydra/launcher=basic
  cov:
    cmds:
      - |
        python {{.main}} -m \
          dataset=cifar10 \
          backbone={{.backbone}} \
          selection=cov \
          selection.fraction=1000,2000,3000,4000 \
          selection.max_epochs=30000 \
          selection.sparse_scale=1e-2 \
          selection.s_lr=1e-2 \
          selection.c=1.05 \
          seed=0,1,2,3,4 \
          hydra/launcher={{.server}}
  random:
    cmds:
      - |
        python {{.main}} -m \
          dataset=cifar10 \
          backbone={{.backbone}} \
          selection=random \
          seed=0,1,2,3,4 \
          selection.fraction=1000,2000,3000,4000 \
          debug={{.debug}} \
          overwrite={{.overwrite}} \
          hydra/launcher={{.server}}
  forgetting:
    desc: "Forget the first 1000 samples"
    cmds:
      - |
        python {{.main}} -m \
          dataset={{.dataset}} \
          backbone={{.backbone}} \
          selection=forgetting \
          selection.fraction=1000,2000,3000,4000 \
          debug=True
          overwrite=True \
          hydra/launcher=basic
  grand:
    cmds:
      - |
        python {{.main}} -m \
          dataset=cifar10 \
          backbone={{.backbone}} \
          selection=grand \
          selection.fraction=1000,2000,3000,4000 \
          seed=0,1,2,3,4 \
          debug={{.debug}} \
          hydra/launcher={{.server}}
  deepcore_uniform:
    cmds:
      - |
        python {{.main}} -m \
          dataset=cifar10 \
          backbone={{.backbone}} \
          selection=deepcore_uniform \
          selection.fraction=1000,2000,3000,4000 \
          seed=0,1,2,3,4 \
          debug={{.debug}} \
          hydra/launcher={{.server}}
  deepcore_forgetting:
    cmds:
      - |
        python {{.main}} -m \
          dataset=cifar10 \
          backbone={{.backbone}} \
          selection=deepcore_forgetting \
          selection.fraction=1000,2000,3000,4000 \
          seed=0,1,2,3,4 \
          debug={{.debug}} \
          hydra/launcher={{.server}}
  deepcore_deepfool:
    cmds:
      - |
        python {{.main}} -m \
          dataset=cifar10 \
          backbone={{.backbone}} \
          selection=deepcore_deepfool \
          selection.fraction=1000,2000,3000,4000 \
          seed=0,1,2,3,4 \
          debug={{.debug}} \
          hydra/launcher={{.server}}
  deepcore_glister:
    cmds:
      - |
        python {{.main}} -m \
          dataset=cifar10 \
          backbone={{.backbone}} \
          selection=deepcore_glister \
          selection.fraction=1000,2000,3000,4000 \
          seed=0,1,2,3,4 \
          debug={{.debug}} \
          hydra/launcher={{.server}}
  deepcore_grand:
    cmds:
      - |
        python {{.main}} -m \
          dataset=cifar10 \
          backbone={{.backbone}} \
          selection=deepcore_grand \
          selection.fraction=1000,2000,3000,4000 \
          seed=0,1,2,3,4 \
          debug={{.debug}} \
          hydra/launcher={{.server}}