method: leverage_score
target: pretrained-finetuned
data_type: eb
seed: 0
fraction: 0.001
use_residual: False
use_raw_G: True
B: 20
gradient_source: finetuned
# Training
max_epochs: 1 # iterative training

# Method-Specific
k: 10                 # sketching
classifier_only: true # NTK 
str: method=${.method}-data_type=${.data_type}-seed=${.seed}-fraction=${.fraction}-k=${.k}-classifier_only=${.classifier_only}-use_residual=${.use_residual}-gradient_source=${.gradient_source}
str_without_fraction: method=${.method}-data_type=${.data_type}-seed=${.seed}-k=${.k}-classifier_only=${.classifier_only}-use_residual=${.use_residual}-gradient_source=${.gradient_source}
