defaults:
  - optimizer: sgd_deepcore
  - scheduler: cosine_annealing_lr
batch_size: 256
max_epochs: 50
optimizer:
  lr: 1e-2

seed: 0
str: batch_size=${.batch_size}-${.optimizer.str}-scheduler=${.scheduler.str}-seed=${.seed}