defaults:
  - submitit_slurm

gres: gpu:1            # use this on the nyu greene cluster instead of partition
timeout_min: 60        # 60min
tasks_per_node: 1
cpus_per_task: 4
nodes: 1
mem_gb: 100
max_num_timeout: 0     # increase if you support requeuing / preemption
gpus_per_node: null    # don't use this, use gres
comment: null          # optionally use this to tell others on the cluster what your job is up to